development:
  domain_name:      <%= ENV["DOMAIN_NAME"] %>
  hostname:         <%= ENV["HOSTNAME"] %>
  smtp_address:     <%= ENV["SMTP_ADDRESS"] %>
  smtp_port:        <%= ENV["SMTP_PORT"] %>
  asset_host:       <%= ENV["ASSET_HOST"] %>
  user_class:       <%= ENV["USER_CLASS"] %>
  cors_whitelist:   <%= ENV["CORS_WHITELIST"] %>
  secret_key_base:  <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base:  <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base:  <%= ENV["SECRET_KEY_BASE"] %>
