source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails',                    '4.2.5'
gem 'sqlite3'
gem 'sass-rails',               '~> 5.0'
gem 'uglifier',                 '~> 2.7'
gem 'coffee-rails',             '~> 4.1'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder',                 '~> 2.4'
gem 'figaro'
gem 'rack-cors',                require: 'rack/cors'
gem 'foreman'

gem 'spree',              '3.0.0'
gem 'spree_gateway',      github: 'spree/spree_gateway',      branch: '3-0-stable'
gem 'spree_auth_devise',  github: 'spree/spree_auth_devise',  branch: '3-0-stable'
gem 'spree_ams',          github: 'hhff/spree_ams',           branch: '3-0-alpha'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc',                   '~> 0.4'
end

group :development do
  gem 'subcontractor'
  gem 'mailcatcher'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'pry-rescue'
  gem 'web-console',            '~> 3.1'
end

group :development, :test do
  gem 'byebug'
end
